## Arrays

In [3]:
import numpy as np

#### array

In [18]:
array1 = np.array([1,2,3,4,5,6], dtype = 'int')
print(type(array1))
array1


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [27]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin=2 )
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

#### Zeros

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### ones

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### range

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])