# Recorrer Arrays

Podemos consultar un campo del array con los carácteres []. Tenemos que recordar que en python, los indices comienzan por cero, por lo que si queremos consultar el primer elemento de un array lo haríamos de la siguiente manera

In [112]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[9])
print(a.shape)
print(a[10])

0
9
(10,)


IndexError: index 10 is out of bounds for axis 0 with size 10

### Slicing

Podemos consultar distintos elementos del array con el slicing. En el slice tenemos que definir: *inicio:fin:paso*

In [113]:
print(a[0:9:2])
print(a[0:8:3])

[0 2 4 6 8]
[0 3 6]


Podemos recuperar los dos últimos elementos, usando valores negativos

In [87]:
a[-2:10]

array([8, 9])

También podemos recorrer los valores de mayor a menor definiendo el tamaño del paso como un nº negativo

In [119]:
a[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

También podemos definir solo el inicio, o el fin

In [120]:
a[:5]

array([0, 1, 2, 3, 4])

In [121]:
a[5:]

array([5, 6, 7, 8, 9])

Para los array multidimensionales funciona del mismo modo. Solo tenemos que verlos en forma de matriz, y consultar la fila y columna que deseemos.

In [143]:
a = np.array([[1,2,3], [3,4,5]], dtype = np.int8)
a

array([[1, 2, 3],
       [3, 4, 5]], dtype=int8)

In [144]:
a[1][0]

3

In [145]:
a[1,0]

3

In [146]:
a[1, 0:2]

array([3, 4], dtype=int8)

In [148]:
a[0:2, 0:2]

array([[1, 2],
       [3, 4]], dtype=int8)

Exactamente igual funciona cuando hablamos de un tipo matrix

In [126]:
print(type(m))
m

<class 'numpy.matrix'>


matrix([[1., 2., 3.],
        [3., 4., 5.]], dtype=float16)

In [127]:
m[0]

matrix([[1., 2., 3.]], dtype=float16)

In [128]:
m[0,1] + m[0,0]

3.0

En la lección anterior conocimimos el tipo nan. También podemos consultar este tipo de dato.

In [137]:
x = np.array([[4, 3], [np.nan, 2.], [np.nan, np.nan]])

print(x[np.isnan(x)])
print(x[~np.isnan(x)])

[nan nan nan]
[4. 3. 2.]


### Indexado booleano

In [151]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

a > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

La operación a > 4 nos devuelve un array de True y False. Este mismo array, lo podemos enviar a nuestro array para realizar una consulta.

In [153]:
a[a>4]

array([5, 6, 7, 8, 9])

Veamos otro ejemplo

In [154]:
bool_array = np.array([True, False,True, False,True, False,True, False,True, False])
a[bool_array]

array([0, 2, 4, 6, 8])

In [155]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [156]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

También actuamos de la misma forma cuando el array es de tipo char

In [157]:
char_array = np.array(['Openwebinars', 'Machine Learning', 'Numpy'])
char_array

array(['Openwebinars', 'Machine Learning', 'Numpy'], dtype='<U16')

In [158]:
char_array[char_array == 'Numpy']

array(['Numpy'], dtype='<U16')

### Recorrido

El objeto iterador nditer, introducido en NumPy 1.6, proporciona muchas formas flexibles de visitar todos los elementos de una o más matrices de forma sistemática. Además del iterador nditer, el cual es un poco más complejo, también podemos recorrer los elementos de un array con un simple bucle for.

In [139]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

for valor in a:
    print(valor)

0
1
2
3
4
5
6
7
8
9


Vamos a usar ahora el iterador *nditer*

In [140]:
for valor in np.nditer(a):
    print(valor)

0
1
2
3
4
5
6
7
8
9
