## Tipos de datos

In [2]:
import numpy as np

In [25]:
a = np.array([1,2,3,4], dtype=np.int_)
a

array([1, 2, 3, 4])

In [34]:
bool_array = np.array([[1,0,0,1], [0,1,1,0]], dtype = np.bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [62]:
char_array = np.array(['a','b','c'], dtype = np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

In [28]:
from sys import getsizeof

a = np.array([1,2,3,4], dtype = np.int8)
b = np.array([1,2,3,4], dtype = np.int64)

print("A", getsizeof(a))
print("B", getsizeof(b))

A 100
B 128


método *dtype*

In [35]:
print(a.dtype)
print(b.dtype)

print(bool_array.dtype)

int8
int64
bool


In [51]:
dt = np.dtype('int32')
print(dt.type)
dt.type is np.int32

<class 'numpy.int32'>


True

In [53]:
dt = np.dtype('f8')
a = np.array([1,2,3,4], dtype = dt)
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [54]:
dt = np.dtype('int32')
dt.kind

'i'

In [55]:
m = np.matrix('1 2 3 ; 4 5 6')
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [58]:
m = np.mat([[1,2,3], [3,4,5]], dtype = np.float16)
m

matrix([[1., 2., 3.],
        [3., 4., 5.]], dtype=float16)

In [61]:
a = np.array([[1,2,3], [3,4,5]], dtype = np.float16)
print(type(a))
m = np.asmatrix(a)
print(type(m))
m

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


matrix([[1., 2., 3.],
        [3., 4., 5.]], dtype=float16)