# Funciones lógicas

In [67]:
import numpy as np

### Condicionales básicas

In [68]:
a = np.array([2,3,4,5])
np.all(a < 10)

True

In [70]:
a = np.array([2,3,4,5])
np.any(a < 0)

False

In [71]:
np.logical_and(a > 2, a < 4)

array([False,  True, False, False])

In [72]:
np.logical_or(a > 2, a < 4)

array([ True,  True,  True,  True])

### Exactamente iguales

In [91]:
np.array_equal(np.array([1,2,3]), np.array([1,2,3]))

True

In [92]:
np.array_equal(np.array([1,2,3]), np.array([1,2,3,4]))

False

### Comparación de valor

In [94]:
np.greater(np.array([1,2,3]), np.array([3,2,1]))

array([False, False,  True])

In [95]:
np.greater_equal(np.array([1,2,3]), np.array([3,2,1]))

array([False,  True,  True])

In [ ]:
np.less(np.array([1,2,3]), np.array([3,2,1]))

array([ True, False, False])

In [97]:
np.less_equal(np.array([1,2,3]), np.array([3,2,1]))

array([ True,  True, False])