# Creación Arrays

In [1]:
import numpy as np

### Unos y ceros

##### eye hace una linea de 1 en diagonal

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### array de unos

In [13]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

##### array de ceros

In [14]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full(shape=(4,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [16]:
np.full(shape=(4,4), fill_value=[10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

### Con datos existentes

In [19]:
np.fromstring('1 2 3 4' , sep = ' ')

array([1., 2., 3., 4.])

In [23]:
datos = np.loadtxt('./datos.txt', delimiter=' ', )
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Rangos 

In [24]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [25]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [ ]:
np.linspace(start=1, stop=10, num = 5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [36]:
np.linspace(start=2, stop= 3.5, num = 10)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ])

In [35]:
np.logspace(start=2, stop= 3.5, num = 10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

- 10 ** 2 = 100
- 10 ** 2.166667 = 146.779
- 10 ** 2.333333 = 215.443

Y así sucesivamente

### Creación de matrices

In [39]:
a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.diag(a)

array([1., 1., 1., 1.])

In [41]:
np.diag(a, k = 1)

array([0., 0., 0.])

In [42]:
np.diagflat(v = [1,2,3,4], k = 0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
np.diagflat(v = [1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
np.tri(N = 5, M = 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [46]:
a = np.array([[1,2,3,4], [4,3,2,1]])
np.asmatrix(a)

matrix([[1, 2, 3, 4],
        [4, 3, 2, 1]])