# Operaciones

In [1]:
import numpy as np

In [5]:
a = np.array(['A', 'B', 'C'], dtype = np.str)
b = np.array(['D', 'E', 'F'], dtype = np.str)

np.char.add(a,b)

array(['AD', 'BE', 'CF'], dtype='<U2')

In [8]:
np.char.multiply(a, [2,3,4])

array(['AA', 'BBB', 'CCCC'], dtype='<U4')

In [13]:
nombres = np.array(['maria', 'antonio', 'francisco'], dtype = np.str)
np.char.capitalize(nombres)

array(['Maria', 'Antonio', 'Francisco'], dtype='<U9')

In [18]:
np.char.replace(nombres, 'mar', 'sof')

array(['sofia', 'antonio', 'francisco'], dtype='<U9')

In [19]:
nombre = np.array(['Mi nombre es Abraham Requena'])
np.char.split(nombre, sep=' ')

array([list(['Mi', 'nombre', 'es', 'Abraham', 'Requena'])], dtype=object)

In [20]:
c = np.array(['  Hola  ', '  Adios '])
np.char.strip(c)

array(['Hola', 'Adios'], dtype='<U8')

### Comparación

In [21]:
a = np.array(['A', 'B', 'C'], dtype = np.str)
b = np.array(['D', 'B', 'F'], dtype = np.str)
np.char.equal(a,b)

array([False,  True, False])

In [26]:
np.char.greater_equal(a,b)

array([False,  True, False])

In [28]:
# less_equal
np.char.less_equal(a,b)

array([ True,  True,  True])

### Info

In [30]:
c = np.array(['Hola', 'Adios'])
np.char.endswith(c, suffix='ios')

array([False,  True])

In [31]:
np.char.startswith(c, prefix='Ad')

array([False,  True])

In [36]:
c = np.array(['HOLA', 'adios'])
np.char.islower(c)

array([False,  True])

In [39]:
c = np.array(['HOLA', 'adios', '123'])
np.char.isdigit(c)

array([False, False,  True])