# Manipulación

### Dimensiones

In [63]:
a = np.array([[1,2,3,4], [4,3,2,1]])
a.shape

(2, 4)

In [64]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [66]:
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [68]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### Tipos de arrays

In [69]:
np.asarray([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [75]:
np.asfarray([1,2,3,4])

array([1., 2., 3., 4.])

In [77]:
np.asfarray([1,2,3,4], dtype = np.int8)

array([1., 2., 3., 4.])

In [80]:
a = [1,2,3,4, np.nan]
np.asarray_chkfinite(a)

ValueError: array must not contain infs or NaNs

In [113]:
a = np.repeat(a = 99, repeats=10)
a

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [114]:
a.reshape((2,5))

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

### Union de arrays

In [89]:
a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a.shape)
print(b.shape)

(2, 4)
(1, 4)


In [90]:
np.concatenate((a,b), axis = 0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [95]:
np.concatenate((a.T, b.T), axis=1)

array([[1, 1, 4],
       [2, 2, 3],
       [3, 3, 2],
       [4, 4, 1]])

In [100]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

np.stack(arrays=(a,b), axis = 1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [101]:
np.stack(arrays=(a,b), axis = 0)

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### Division de arrays

In [105]:
a = np.arange(0, 20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
np.split(a, indices_or_sections=4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [109]:
np.split(a, [3, 5, 10, 16])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

### Añadir y eliminar

In [115]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [121]:
np.insert(a, obj=4, values=[5,6])

array([1, 2, 3, 4, 5, 6])

In [120]:
np.insert(a, obj=1, values=[5,6])

array([1, 5, 6, 2, 3, 4])

In [124]:
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

In [127]:
np.delete(a, obj = 3)

array([1, 2, 3])

In [128]:
a = np.array([0, 0, 0, 0, 1, 2, 3, 4, 0, 0])
np.trim_zeros(a)

array([1, 2, 3, 4])

In [130]:
a = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
np.unique(a)

array([1, 2, 3])