# Funciones matemáticas

In [98]:
import numpy as np

#### Redondeo

In [107]:
a = 2.49264

In [108]:
np.round(a, 1)

2.5

In [112]:
array = np.array([1.435, 13.1435, 4.916])
np.round(array, 2)

array([ 1.44, 13.14,  4.92])

In [115]:
np.floor(array)

array([ 1., 13.,  4.])

In [116]:
np.ceil(array)

array([ 2., 14.,  5.])

### Sumas y productos

In [117]:
b = np.array([2,3,4])
np.prod(b)

24

In [126]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b, axis = 0)

array([4, 6, 8])

In [127]:
np.prod(b, axis = 1)

array([24,  8])

In [129]:
np.sum(b)

15

In [132]:
np.sum(b, axis = 0)

array([4, 5, 6])

In [131]:
np.sum(b, axis = 1)

array([9, 6])

#### Exponentes y logaritmos

In [134]:
b

array([[2, 3, 4],
       [2, 2, 2]])

In [135]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

#### Logaritmos

In [142]:
p = np.power(np.e, b)
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [143]:
np.log10(b)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [144]:
np.power(10, np.log10(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

In [145]:
np.log2(b)

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

In [146]:
np.power(2, np.log2(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

### Operaciones aritméticas

In [155]:
a = np.array([[1,2,3,4], [4,3,2,1]])
b = np.array([4,3,2,1])

In [156]:
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [157]:
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [158]:
np.multiply(a,b)

array([[ 4,  6,  6,  4],
       [16,  9,  4,  1]])

In [162]:
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])